apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ekart
          image: harry1019/ShoppingCard:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070

---

apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc
spec:
  selector:
    app: ekart
  type: NodePort
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30186  # You can change this if needed
